
joint : 50001,
	total joint,
	40000,
		position,             reference, node, null,
		position orientation, reference, node, eye,
		rotation orientation, reference, node, eye,
	50001,
		position,             reference, other node, null,
		position orientation, reference, other node, eye,
		rotation orientation, reference, other node, eye,
	position constraint,
		active, active, active,
			null,
	orientation constraint,
		active, active, active,
			null;

joint : 50002,
	total joint,
	40000,
		position,             reference, node, null,
		position orientation, reference, node, eye,
		rotation orientation, reference, node, eye,
	50002,
		position,             reference, other node, null,
		position orientation, reference, other node, eye,
		rotation orientation, reference, other node, eye,
	position constraint,
		active, active, active,
			null,
	orientation constraint,
		active, active, active,
			null;

joint : 50003,
	total joint,
	40000,
		position,             reference, node, null,
		position orientation, reference, node, eye,
		rotation orientation, reference, node, eye,
	50003,
		position,             reference, other node, null,
		position orientation, reference, other node, eye,
		rotation orientation, reference, other node, eye,
	position constraint,
		active, active, active,
			null,
	orientation constraint,
		active, active, active,
			null;

